### ISSUE TITLE
RFE: Add support for Archive file format

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/packages-formula#25]
Computer files, used for purpose of software bundle distribution, are basically **packages**.  Could we add generic support for [Archive file](https://en.wikipedia.org/wiki/Archive_file) format, and specifically  tarball format installation?   

Handling archive file format is very consistent across formats. Could I suggest following-

**New States**

`packages.archive.wanted`
- prepare tmp-dir (`file.directory`)
- download archive to tmp-dir (`cmd.run`)
- checksum archive in tmp-dir  (`module-run.checksum`)
- extract archive to DEST   (`archive.extracted` or `cmd.run`)
- cleanup tmp-dir/archive  (`file.absent`)

`packages.archive.unwanted`
- cleanup DEST (`file.absent`)

**New Pillars**
```
packages:
  archive:
     wanted:
        bob:
            source:  http://repo.org/release/bob_latest.tar.gz
            dest: /opt/bob/
            format: tarball
     unwanted:
       - /opt/peter/
```

**New format support**

- Tarball  (tar.gz)
