### ISSUE TITLE
RFE: Pinning packages by name

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/packages-formula#8]
The 2/21 Ubuntu kernel upgrade fiasco *bashed* a bunch of my machines, breaking a kernel module.

 https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/1750937

I wonder could this formula have a "pin" and "unpin" package-by-name feature?  Supporting any package managers (yum/zypp/apt) which have **hold** and **unhold** support?

**Comment by javierbertoli** [comment]
what do you think of this approach:

```yaml
packages:
  pkgs:
    pinned:
        - alien: '8.95'
        - apparmor: '2.12-3'
    wanted:
      - git
      - fail2ban
    unwanted:
      - avahi-daemon
```

That way, we install *specific versions* of packages in the `pinned` dict and *hold* them.

If you want to later `unpin` it, just move it back to the `wanted` list and that's it (we can add the *unhold* attribute to those packages).

Will this cover what you propose?
